"""
NOTE - URLS we have

http://127.0.0.1:8000/admin/
http://127.0.0.1:8000/jobs/portal/
http://127.0.0.1:8000/jobs/jobtitles/
http://127.0.0.1:8000/jobs/<job_id>/



http://127.0.0.1:8000/jobs/jobtitles  (PLURAL endpoint)
http://127.0.0.1:8000/jobs/jobtitles/1/ (SINGULAR endpoint)

"""

from django.urls import path, re_path
from . import views, views_v2, views_v3, views_v4

urlpatterns = [
    re_path(r"^wel*", views.welcome, name="welcome"),
    path("portal/", views.get_portal_details, name="portal_details"),
    path("jobtitles/", views.job_titles, name="jobtitle"),
    path("jobtitles/<int:job_id>/", views.get_job_description, name="JD"),
    path("v2/applicants/",
         views_v2.ApplicantList.as_view(),
         name="ap_list"),
    # template name is generated by django (jobs/applicant_list.html).
    # the “jobs” part comes from the name of the app that defines the model,
    # while the “applicant” bit is the lowercased version of the model’s name.

    path("v2/applicants/update/<pk>",
         views_v2.ApplicantUpdate.as_view(),
         name="ap_update"),  # default template name - 'jobs/applicant_form.html'.

    path("v2/applicants/create/", views_v2.ApplicantCreate.as_view(),
         name="ap_create"),

    path("v2/applicants/delete/<pk>",views_v2.ApplicantDelete.as_view(),
         name="ap_delete"),

    path("v2/applicants/details/<pk>", views_v2.ApplicantDetails.as_view(),
         name="ap_details"),

    path("v3/applicants/", views_v3.Applicants.as_view()),
    path("v4/jobtitles/", views_v4.jobtitle_list, name="v4_jobtitles_list")
]